
POST http://localhost:8080/posts/
content-type: application/json

{
  "title": "React On Page Scroll Progress Bar with Web",
  "body": "Do you want to display a progress bar on page scroll in React application? Well, then you are at the right place. We are going to build a progress bar only using pure JavaScript and CSS in a React 16+ application.",
  "author": "tom"
}

###

GET http://localhost:8080/posts/
###

POST http://localhost:8080/posts/comment
content-type: application/json

{
  "commentBody": "Good art34icle11111111111111",
  "authorId": "5f48fe19a84dea00126cbd3a",
  "postId": "5f511c331d1835013013523f"
}

###


PATCH  http://localhost:8080/posts/5f49001fca36fb004218bf5e
content-type: application/json

{
  "title": "New title2",
  "body": "Lorem ipsum"
}
###

DELETE http://localhost:8080/posts/5f511b83e736db00a2823789




// register

###
POST http://localhost:8080/register
content-type: application/json

{
  "name": "Luck",
  "lastName": "Skywalker",
  "email": "lucksk@star0.com",
  "password": "darthwader",
  "role": 0
}
//login form
################################################################

POST http://localhost:8080/login
content-type: application/json

{
   "email": "lucksk@star0.com",
  "password": "darthwader"
}

###